# Assignment 3

Task 1.1

In [40]:
def divide(x, y): 
    try:
        result = x // y 
        print("Your answer is :", result) 
    except ZeroDivisionError: 
        print("You are dividing by zero ") 

x = int(input("Enter number"))
y= int(input("Enter number"))

divide(x,y)

Enter number23
Enter number45
Your answer is : 0


Task 1.2

In [39]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"] 

op = [[x,y,z] for x in subjects for y in verbs for z in objects]

for i in op:
    print(" ".join(i))


Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


Task 2.1

In [105]:
n = int(input("Enter number of column\n"))
b = [1,2,3,4,5]
v = []
for x in range(n):
    v.append([num**x for num in b])

npv = np.array(v)
ntr = np.transpose(npv)
print(ntr)

Enter number of column
4
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]
